# Generated by Django 2.2.12 on 2022-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('type', models.SmallIntegerField(choices=[(1, '学生'), (2, '老师'), (3, '管理员')], verbose_name='用户类型')),
            ],
        ),
    ]
