# Generated by Django 2.2.12 on 2022-11-04 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0002_auto_20221104_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Student', serialize=False, to='baweb.User', verbose_name='学生')),
                ('name', models.CharField(blank=True, default='未上传名字', max_length=64, verbose_name='名字')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别')),
                ('email', models.EmailField(blank=True, default='*****@163.com', max_length=64, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default='未知', max_length=16, verbose_name='手机号')),
                ('student_profile_pic', models.ImageField(blank=True, upload_to='../media/userimg/student_profile_pic', verbose_name='头像')),
            ],
        ),
    ]
