# Generated by Django 2.2.12 on 2022-11-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0005_auto_20221108_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='课件')),
                ('file_name', models.CharField(blank=True, default=None, max_length=64, verbose_name='课件名')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_course', to='baweb.Course', verbose_name='所属课程')),
                # 新增 resource_intro 字段，存储资源简介，设置非空约束
                ('resource_intro', models.TextField(verbose_name='资源简介', blank=False)),
                # 新增 category_name 字段，存储类别名称
                ('category_name', models.CharField(max_length=50, verbose_name='类别名称', blank=True)),
                # 新增 upload_time 字段，存储资源上传时间，自动记录当前时间
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                # 新增 lesson_id 字段，关联到课节表，可为空
                ('lesson_id', models.IntegerField(verbose_name='所属课节', null=True)),
            ],
        ),
    ]
