# Generated by Django 2.2.12 on 2022-11-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0006_coursefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefiles',
            name='file_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='课件名'),
        ),
    ]
