# Generated by Django 2.2.12 on 2022-12-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0013_group_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='submit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='组名'),
        ),
    ]
