# Generated by Django 2.2.12 on 2022-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0014_auto_20221201_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='是否是小组任务'),
        ),
    ]
