# Generated by Django 2.2.12 on 2023-01-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0015_assignment_is_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='评论')),
                ('created_at', models.DateField(auto_now=True, verbose_name='评价时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_course', to='baweb.Course', verbose_name='所属课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursecomment_user', to='baweb.User', verbose_name='评价人')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
