# Generated by Django 2.2.12 on 2023-01-13 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0017_announce'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDisabled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_disabled', to='baweb.User', verbose_name='禁用教师')),
            ],
        ),
    ]
