# Generated by Django 4.1.5 on 2023-01-13 04:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baweb", "0018_teacherdisabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="description_richtext",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="任务简介"),
        ),
        migrations.AddField(
            model_name="course",
            name="description_richtext",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="课程简介"),
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="description_richtext",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="教师简介"),
        ),
    ]
