# Generated by Django 4.1.5 on 2023-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baweb", "0019_assignment_description_richtext_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherinfo", options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="order",
            field=models.IntegerField(blank=True, default=0, verbose_name="顺序"),
        ),
    ]
