# Generated by Django 4.1.5 on 2023-02-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baweb", "0020_alter_teacherinfo_options_teacherinfo_order"),
    ]

    operations = [
        migrations.AlterModelOptions(name="course", options={"ordering": ["order"]},),
        migrations.AddField(
            model_name="course",
            name="order",
            field=models.IntegerField(blank=True, default=0, verbose_name="课程顺序"),
        ),
    ]
